#!/usr/bin/env bash
# parses apache log files in list format
#   Sort visitors by IP and HTTP status code
#   Displays the number of occurance, IP and HTTP status
#+  code of each log, in sorted order

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
